# Generated by Django 4.2 on 2025-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')]),
        ),
    ]
