# Generated by Django 4.2 on 2025-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0002_remove_vote_comment_alter_vote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='card_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='team_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
