# Generated by Django 4.2 on 2025-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0003_vote_card_name_vote_team_name_vote_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='code_quality',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')], null=True, verbose_name='Code Quality'),
        ),
        migrations.AddField(
            model_name='vote',
            name='communication',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')], null=True, verbose_name='Communication'),
        ),
        migrations.AddField(
            model_name='vote',
            name='project_timeline',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')], null=True, verbose_name='Project Timeline'),
        ),
        migrations.AddField(
            model_name='vote',
            name='sprint_progress',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')], null=True, verbose_name='Sprint Progress'),
        ),
        migrations.AddField(
            model_name='vote',
            name='team_collaboration',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')], null=True, verbose_name='Team Collaboration'),
        ),
        migrations.AddField(
            model_name='vote',
            name='work_environment',
            field=models.IntegerField(blank=True, choices=[(1, 'Green'), (2, 'Amber'), (3, 'Red')], null=True, verbose_name='Work Environment'),
        ),
    ]
