# Generated by Django 4.2 on 2025-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0004_remove_vote_card_name_remove_vote_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='code_quality',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='project_timeline',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='sprint_progress',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='team_collaboration',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='work_environment',
        ),
        migrations.AddField(
            model_name='vote',
            name='Team_Progress',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='Code_Quality',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='Communication',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='Project_Timeline',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='Team_Collaboration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='Work_Environment',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
